version: '3'
services: 
  app: 
    container_name: newegg-addtocart
    restart: always
    # Always restart the container if it stops. If it is manually stopped, it is restarted only when Docker daemon restarts or the container itself is manually restarted.
    build: .
    ports: 
      - '80:3005'
    links:
      - mongo 
    # volumes:
    #   - .:/code
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'